name: Benchmark

on: [push, pull_request_target, workflow_dispatch]

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: |
              src/riscv.c
              src/decode.c
              src/emulate.c
              src/rv32_template.c
              src/rv32_constopt.c
      - name: install-dependencies
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
            github.event_name == 'workflow_dispatch'}}
        run: |
            sudo pip3 install numpy
        shell: bash
      - name: default build
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
            github.event_name == 'workflow_dispatch'}}
        run: make
      - name: Run benchmark
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
            github.event_name == 'workflow_dispatch'}}
        run: |
          tests/bench-aggregator.py

